#! usr/bin/env python

import nibabel as nib
from dipy.align.reslice import reslice
import argparse

if __name__ == '__main__':
    parser = argparse.ArgumentParser('This script allows you to resample images with new resolutions')
    parser.add_argument('img', help='input image to be resampled')
    parser.add_argument('factor', help= 'factor to resample by: a factor of 2 will double the image size, a factor of 1/2 will half the image size')
    parser.add_argument('output', help='filename of the output image')
    args = parser.parse_args()

    img = nib.load(args.img)
    zooms = img.header.get_zooms()[:3]
    new_zooms = [x / float(args.factor) for x in zooms]
    newdata, newaff = reslice(img.get_data(), img.affine, zooms, new_zooms) 
    new_img_nii = nib.Nifti1Image(newdata, newaff)
    print('saving resampled image at', args.output)
    nib.save(new_img_nii, args.output)
